# Generated by Django 4.0.4 on 2022-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('group_desc', models.TextField()),
                ('flavour_name', models.CharField(max_length=50)),
                ('flavour_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
