# Generated by Django 4.0.4 on 2022-05-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavours',
            new_name='Flavour',
        ),
    ]
