# Generated by Django 4.0.4 on 2022-05-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_product', '0002_rename_flavours_flavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('group_desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='flavour',
            name='group',
        ),
        migrations.RemoveField(
            model_name='flavour',
            name='group_desc',
        ),
    ]
