# Generated by Django 4.0.4 on 2022-05-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_home', '0002_update_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='logo',
        ),
    ]
