# Generated by Django 4.0.4 on 2022-05-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_home', '0003_remove_update_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='HomeEdit',
        ),
    ]
