# Generated by Django 4.0.4 on 2022-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
