# Generated by Django 4.0.4 on 2022-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_contact', '0002_messagebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='mail_box',
            field=models.CharField(max_length=200),
        ),
    ]
