# Generated by Django 4.0.4 on 2022-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_title', models.CharField(max_length=200)),
                ('side_text', models.TextField()),
                ('main_title', models.CharField(max_length=200)),
                ('main_text', models.TextField()),
            ],
        ),
    ]
