# Generated by Django 4.0.4 on 2022-05-30 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
