# Generated by Django 4.0.4 on 2022-05-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_about', '0002_update_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='main_image',
        ),
    ]
