# Generated by Django 4.0.4 on 2022-05-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froyo_about', '0003_remove_update_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200)),
                ('main_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_title', models.CharField(max_length=200)),
                ('side_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
